jobs: 

- job: 'SonarAnalisys'
  steps:
  - task: SonarQubePrepare@4
    inputs:
        SonarQube: 'mySonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'nodejs'
        cliProjectName: 'nodejs'
        cliAdditionalArgs: >
          sonar.sources=src
          sonar.tests=src/__test__ 
          sonar.exclusions=src/__test__/**
          sonar.testExecutionReportPaths=./test-report.xml 
          sonar.javascript.lcov.reportPaths=coverage/lcov.info"

  - task: SonarQubeAnalyze@4
    displayName: 'Run SonarQube analysis'

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'