stages:

- stage: 'build'
  displayName: 'Build app node js'
  jobs: 
  - template: '01-Build/01-BuildApp.yml'

# - stage: 'Test'
#   displayName: 'Test'
#   jobs: 
#   - template: '02-Test/01-TestNodejs.yml'

- stage: 'Analisys'
  displayName: 'Analisys with sonar'
  jobs: 
  - template: '03-Sonar/01-SonarAnalisys.yml'