stages:

- stage: 'build'
  displayName: 'Build app node js'
  jobs: 
  - template: '01-Build/01-BuildApp.yml'
  - template: '02-Test/01-TestNodejs.yml'
  - template: '03-Sonar/01-SonarAnalisys.yml'

