parameters:
  - name: library
    type: string

variables:
  - name: library
    value: ${{parameters.library}}

stages:

- stage: 'build'
  displayName: 'Build app'
  jobs: 
  - template: '01-build/01-build.yml'

- stage: 'test'
  displayName: 'test app'
  jobs: 
  - template: '02-test/01-test.yml'

- stage: 'package'
  displayName: 'package artifact'
  jobs: 
  - template: '03-package/01-package.yml'

# - stage: 'scan_sonarqube'
#   displayName: 'scan sonarqube'
#   jobs: 
#   - template: '04-sonarqube/01-sonarqube.yml'

- stage: 'docker_image'
  displayName: 'Build image docker'
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs: 
  - template: '05-buildocker/01-buildocker.yml'

- stage: 'deploy'
  displayName: 'deploy app nodejs'
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs: 
  - template: '06-deploy/01-deploy.yml'

- stage: 'upload_dockerhub'
  displayName: 'upload image dockerhub'
  jobs: 
  - template: '07-upload/01-upload.yml'

# - stage: 'owasp'
#   displayName: 'analysis with owasp'
#   condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
#   jobs: 
#   - template: '08-owasp/01-owasp.yml'