jobs:

- job: 'BuildNodeJS'
  displayName: 'Build'
  steps:
  # - task: NodeTool@1
  #   inputs:
  #     version: '16.x'
  #   displayName: 'Install Node.js'

  - script: |
      npm install
      npm install --save-dev jest
    displayName: 'npm install'

  - script: |
      npm run build
      echo $(Build.ArtifactStagingDirectory)
    displayName: 'npm build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'MyApp'
      publishLocation: 'Container'
