jobs:

- job: 'BuildNodeJS'
  displayName: 'Build'
  steps:
  # - task: NodeTool@1
  #   inputs:
  #     version: '16.x'
  #   displayName: 'Install Node.js'

  - script: |
      npm install
      npm install --save-dev jest
    displayName: 'npm install'

  - script: |
      npm run build
      echo $(Build.ArtifactStagingDirectory)
      echo $(System.DefaultWorkingDirectory)
      echo $(Build.SourcesDirectory)
    displayName: 'npm build'

  - task: CopyFiles@2
    inputs:
      contents: '*'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Myapp
