jobs:

- job: 'BuildNodeJS'
  displayName: 'Build'
  steps:
  - script: |
      npm install
      npm install --save-dev jest
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'

- job: 'Test'
  displayName: 'Test app'
  steps: 
  - script: |
        npm test
    displayName: 'unit test'

- job: 'Analisys'
  displayName: 'Analisys with sonar'
  steps: 
  - task: SonarQubePrepare@4
    inputs:
        SonarQube: 'mySonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'nodejs'
        cliProjectName: 'nodejs'
        cliAdditionalArgs: >
          sonar.sources=src
          sonar.tests=src/__test__ 
          sonar.exclusions=src/__test__/**
          sonar.testExecutionReportPaths=./test-report.xml 
          sonar.javascript.lcov.reportPaths=coverage/lcov.info"

  - task: SonarQubeAnalyze@4
    displayName: 'Run SonarQube analysis'

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'