jobs:
- job: 'package'
  displayName: 'package app'
  steps: 
  - checkout: none
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/dist/*'
      artifact: 'nodejsapp'
      publishLocation: 'pipeline'