jobs:
- job: 'analysis'
  displayName: 'analysis with sonar'
  pool:
    vmImage: 'ubuntu-latest'
  steps: 

  - task: SonarQubePrepare@4
    inputs:
        SonarQube: 'mySonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'nodejs'
        cliProjectName: 'nodejs'
        cliAdditionalArgs: >
          sonar.sources=$(Build.SourcesDirectory)/src
          # sonar.tests=$(Build.SourcesDirectory)/src/__test__ 
          # sonar.exclusions=$(Build.SourcesDirectory)/src/__test__/**
          # sonar.testExecutionReportPaths=$(Build.SourcesDirectory)/test-report.xml 
          # sonar.javascript.lcov.reportPaths=$(Build.SourcesDirectory)/coverage/lcov.info"

  - task: SonarQubeAnalyze@4
    displayName: 'Run SonarQube analysis'

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'